[pytest]
testpaths = tests
pythonpath = .
asyncio_mode = strict
markers =
    smoke: mark test as smoke test
    regression: mark test as regression test
    integration: mark test as integration test
    unit: mark test as unit test
    asyncio: mark test as async
